site_name: Intelligent App Factory
site_description: The Intelligent App Factory (IAF) is a collection of best practices, tools, and guidance to help you build intelligent applications with confidence.
site_author: Logan Talbot
site_url: https://intelligentappfactory.com
site_keywords: Intelligent App Factory, IAF, AI, ML, Machine Learning, Artificial Intelligence, Responsible AI, Well-architected Framework, Security, Reference Architecture, Azure, AWS, GCP, Google Cloud, AWS, Amazon Web Services, Microsoft Azure, Google Cloud Platform, MLOps, DevOps, DataOps, AIOps, Data Science, Data Engineering, Data Analytics, Data Governance, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights, Data Intelligence, Data Strategy, Data Governance, Data Management, Data Architecture, Data Engineering, Data Science, Data Analytics, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights, Data Intelligence, Data Strategy, Data Governance, Data Management, Data Architecture, Data Engineering, Data Science, Data Analytics, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights, Data Intelligence, Data Strategy, Data Governance, Data Management, Data Architecture, Data Engineering, Data Science, Data Analytics, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights
theme:
  name: material
  language: en
  logo: images/branding/iaf-logo-white-transparent-500.png
  favicon: images/branding/iaf-logo-white-transparent-500.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra: 
  generator: false
  analytics:
    provider: google
    property: G-7L20HYSPTB
extra_css:
  - stylesheets/extra.css
plugins:
  - blog
  - tags
  - search
nav:
  - Welcome: index.md
  - Getting Started:
    - Learn Intelligent App: getting-started/learn-intelligent-apps.md
  - Components:
    - Overview: components/overview.md
  - Concepts:
    - Overview: concepts/overview.md
    - AI Charters: concepts/ai-charters.md
  - Well-architected Framework: well-architected-framework.md
  - Security: security.md
  - Responsible AI: responsible-ai.md
  - Application Lifecycle: intelligent-app-lifecycle.md
  - Recommended Certifications: certifications.md
  - Reference Architecture:
    - Overview: reference-architecture/overview.md
    - Azure:
        Overview: reference-architecture/azure/overview.md
  - Resources: resources.md
  - News Archive: news-archive.md
  - Blog:
    - blog/index.md