site_name: Intelligent App Factory
site_description: The Intelligent App Factory (IAF) is a collection of best practices, tools, and guidance to help you build intelligent applications with confidence.
site_author: Logan Talbot
site_url: https://intelligentappfactory.com
site_keywords: Intelligent App Factory, IAF, AI, ML, Machine Learning, Artificial Intelligence, Responsible AI, Well-architected Framework, Security, Reference Architecture, Azure, AWS, GCP, Google Cloud, AWS, Amazon Web Services, Microsoft Azure, Google Cloud Platform, MLOps, DevOps, DataOps, AIOps, Data Science, Data Engineering, Data Analytics, Data Governance, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights, Data Intelligence, Data Strategy, Data Governance, Data Management, Data Architecture, Data Engineering, Data Science, Data Analytics, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights, Data Intelligence, Data Strategy, Data Governance, Data Management, Data Architecture, Data Engineering, Data Science, Data Analytics, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights, Data Intelligence, Data Strategy, Data Governance, Data Management, Data Architecture, Data Engineering, Data Science, Data Analytics, Data Privacy, Data Security, Data Protection, Data Ethics, Data Bias, Data Fairness, Data Explainability, Data Transparency, Data Accountability, Data Trust, Data Quality, Data Lineage, Data Catalog, Data Lake, Data Warehouse, Data Mart, Data Pipeline, Data Model, Data Schema, Data Transformation, Data Ingestion, Data Storage, Data Processing, Data Analysis, Data Visualization, Data Reporting, Data Insights

# Home.html

repo_name: IntelligentAppFactory
repo_url: https://github.com/LoganDavidTalbot/IntelligentAppFactory
copyright: © 2024 | Logan Talbot


# Custom Homepage Elements
home_cover_image: images\branding\IAF 2 transparent.png # This path starts at your root mkdocs directory. 
home_tagline: Unleash your potential!
home_description: |
  Your gateway to building smarter, faster, and more efficient intelligent applications. 

# Gradient Color 
#home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)
 
# Main Buttons
home_button_primary_name: Explore
home_button_primary_url: about
home_button_primary_theme: md-button md-button--primary
home_button_secondary_name: What is an intelligent app?
home_button_secondary_url: what-is-an-intelligent-app
home_button_secondary_theme: md-button # Options: "md-button", "md-button md-button--primary" 

# Custom Homepage Button(s)
home_button1_name: Learn                         # Comment this parameter out to remove the button.
home_button1_url: getting-started/learn-intelligent-apps/                          # This path starts at your root mkdocs directory.
home_button1_blurb: |                            # Short description of this button / section.
  From beginner-friendly resources to advanced AI concepts, we've got everything you need to master the art of intelligent app development.

home_button2_name: Develop  # Comment this parameter out to remove the button.
home_button2_url: components/overview/   # This path starts at your root mkdocs directory.  
home_button2_blurb: |         # Short description of this button / section. 
  Explore our rich resources designed to empower your intelligent app development journey.

home_button3_name: Architect   # Comment this parameter out to remove the button.
home_button3_url: reference-architecture/overview/    # This path starts at your root mkdocs directory.
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  Unleash the power of AI with our comprehensive resources for architecting intelligent apps.

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage   
  console.log("This is an example!");

# Theme

theme:
  name: material
  custom_dir: assets # Contains custom 'home.html' coverpage (and 'main.html')
  language: en
  logo: images/branding/iaf-logo-white-transparent-500.png
  favicon: images/branding/iaf-logo-white-transparent-500.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra: 
  generator: false
  analytics:
    provider: google
    property: G-7L20HYSPTB
extra_css:
  - stylesheets/extra.css
plugins:
  - blog
  - tags
  - search
nav:
  - Home: index.md
  - About: about.md
  - What is an intelligent app?: what-is-an-intelligent-app.md
  - Getting Started:
    - Learn Intelligent App: getting-started/learn-intelligent-apps.md
  - Components:
    - Overview: components/overview.md
  - Concepts:
    - Overview: concepts/overview.md
    - AI Charters: concepts/ai-charters.md
  - Well-architected Framework: well-architected-framework.md
  - Security: security.md
  - Responsible AI: responsible-ai.md
  - Application Lifecycle: intelligent-app-lifecycle.md
  - Recommended Certifications: certifications.md
  - Reference Architecture:
    - Overview: reference-architecture/overview.md
    - Azure:
        Overview: reference-architecture/azure/overview.md
  - Resources: resources.md
  - News Archive: news-archive.md
  - Blog:
    - blog/index.md