site_name: Intelligent App Factory
theme:
  name: material
  language: en
  logo: images/branding/iaf-logo-white-transparent-500.png
  favicon: images/branding/iaf-logo-white-transparent-500.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra: 
  generator: false
extra_css:
  - stylesheets/extra.css
nav:
  - Welcome: index.md
  - Getting Started:
    - Learn Intelligent App: getting-started/learn-intelligent-apps.md
  - Concepts:
    - Overview: concepts/overview.md
  - Well-architected:
    - Overview: well-architected/overview.md
    - Security: well-architected/security.md
    - Responsible AI: well-architected/responsible-ai.md
    - Reliability: well-architected/reliability.md
    - Operational Excellence: well-architected/operational-excellence.md
    - Performance efficiency: well-architected/performance-efficiency.md
    - Cost Optimization: well-architected/cost-optimization.md
    - Sustainability: well-architected/sustainability.md
  - Reference Architecture:
    - Overview: reference-architecture/overview.md
  - Resources: resources.md
  - news-archive: news-archive.md